cli_script.sh "enable ns feature appflow"
cli_script.sh "enable ns mode ulfd"
cli_script.sh "add dns nameserver 10.244.3.3"
cli_script.sh "add dns nameserver 10.244.3.2"
cli_script.sh "add server logproxysvr logproxy.tracing.svc.cluster.local"
cli_script.sh "add service logproxysvc logproxysvr LOGSTREAM 5557"
cli_script.sh "set appflow param -templateRefresh 60 -SecurityInsightRecordInterval 60 -httpUrl ENABLED -httpCookie ENABLED -httpReferer ENABLED -httpMethod ENABLED -httpHost ENABLED -httpUserAgent ENABLED -httpContentType ENABLED -SecurityInsightTraffic ENABLED -httpQueryWithUrl ENABLED -urlCategory ENABLED -observationPointId 2540398090 -distributedTracing ENABLED -distTracingSamplingRate 100"
cli_script.sh "bind cs vserver k8s-10.244.1.37:80:http -analyticsprofile ns_analytics_default_http_profile"
cli_script.sh "bind cs vserver k8s-10.244.1.37:80:http -analyticsprofile ns_analytics_default_tcp_profile"
cli_script.sh "bind cs vserver k8s-10.244.1.37:443:ssl -analyticsprofile ns_analytics_default_http_profile"
cli_script.sh "bind cs vserver k8s-10.244.1.37:443:ssl -analyticsprofile ns_analytics_default_tcp_profile"
cli_script.sh "set analyticsprofile ns_analytics_default_http_profile -httpURL enabled -httphost enabled -httpMethod ENABLED -httpUserAgent ENABLED -urlCategory ENABLED -httpContentType ENABLED -httpVia ENABLED -httpDomainName ENABLED -httpURLQuery ENABLED -collectors logproxysvc"
cli_script.sh "set analyticsprofile ns_analytics_default_tcp_profile  -collectors logproxysvc"
cli_script.sh "add ntp server 91.219.89.218 -minpoll 5 -maxpoll 10"
cli_script.sh "enable ntp sync"
cli_script.sh "set servicegroup k8s-watches-ingress.tracing.80.k8s-amazon.tracing.1719.svc -maxclient 100"
cli_script.sh "set servicegroup k8s-watches-ingress.tracing.80.k8s-fasttrack.tracing.1720.svc -maxclient 100"
cli_script.sh "set servicegroup k8s-watches-ingress.tracing.80.k8s-titan.tracing.1721.svc -maxclient 100"
cli_script.sh "set servicegroup k8s-watches-ingress.tracing.80.k8s-casio.tracing.1722.svc -maxclient 100"
cli_script.sh "set servicegroup k8s-watches-ingress.tracing.80.k8s-sonata.tracing.1723.svc -maxclient 100"
cli_script.sh "add ssl certKey cert1 -cert \"/nsconfig/ssl/ns-root.cert\" -key \"/nsconfig/ssl/ns-root.key\""
cli_script.sh "bind ssl vserver k8s-10.244.1.37:443:ssl -certkey cert1"
cli_script.sh "unbind ssl vserver k8s-10.244.1.37:443:ssl -cipherName DEFAULT"
cli_script.sh "bind ssl vserver k8s-10.244.1.37:443:ssl -cipherName ALL"
