imports:
- path: template.py
resources:
- name: citrix-adc-3nic-deployment
  type: template.py
  properties:
   #The Google Region where the Citrix ADC would be deployed. Example: asia-northeast1
   region: "asia-northeast1"
   #The availability zone in the region where the Citrix ADC would be deployed.
   #Example: asia-northeast1-b
   google_zone: "asia-northeast1-b"
   #The network to deploy the Citrix ADC
   mgmt_network: "vpx-snet-mgmt"
   #Subnet for the management interface
   mgmt_subnet: "vpx-snet-mgmt"
   #Ports to open to process management traffic
   mgmt_ports:
       - "22"
       - "80"
       - "443"
   #Network for the nic used to handle client side traffic
   client_network: "vpx-snet-vip"
   #Subnet in the specified network to handle client side traffic
   client_subnet: "vpx-snet-vip"
   #Network for the nic used to handle server side traffic
   server_network: "vpx-snet-snip"
   #Subnet in the specified network to handle server side traffic
   server_subnet: "vpx-snet-snip"
   #Ports to open to process client/server traffic
   traffic_ports:
       - "80"
       - "22"
       - "443"
       - "8080"
   #The Citrix ADC image name
   image_name: "netscaler12-1"
   #The project name where the image is hosted
   image_project_name: "<your project name>"
   #The instance type to deploy the Citrix ADC instance Example: n1-standard-4
   instance_type: "n1-standard-4"
   #The public key used for authenticating into the Citrix ADC.
   #Specify values separated by \n to specify more than one user.
   #Set it to "" if you wish to specify no key
   ssh_public_key: ""
   #Specify a service account. If not, leave the field blank.
   service_account: ""
   #Enter "yes" if you would like a public ip to be associated to the NIC.
   assign_public_ip: "yes"