apiVersion: v1
kind: Service
metadata:
  labels:
    name: statefulset-primary
  name: statefulset-primary
  namespace: "{{ .Release.Namespace }}"
spec:
  ports:
  - port: {{.Values.container.port}}
    protocol: TCP
    targetPort: {{.Values.container.port}}
  selector:
    name: statefulset-primary
  sessionAffinity: None
  type: "{{.Values.serviceType}}"
