apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: statefulset
  name: pgdata-statefulset-0
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.storage.size}}
  volumeName: statefulset-pgdata-0
  storageClassName: pg-storage-0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: statefulset
  name: pgdata-statefulset-1
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.storage.size}}
  volumeName: statefulset-pgdata-1
  storageClassName: pg-storage-1
