apiVersion: v1
kind: Pod
metadata:
  name: cic-vpx
  labels:
    app: cic-vpx
spec: 
      serviceAccountName: cpx
      containers:
      - name: cic-vpx
        image: "in-docker-reg.eng.citrite.net/cic-dev/cic:280"
        env:
         # Set NetScaler NSIP/SNIP, SNIP in case of HA (mgmt has to be enabled) 
         - name: "NS_IP"
           value: "10.217.212.246"
         - name: "NS_VIP"
           value: "10.217.212.239"
         # Set username for Nitro
         # Set log level
         - name: "NS_ENABLE_MONITORING"
           value: "NO"
         - name: "NS_USER"
           value: "nsroot"
         - name: "NS_PASSWORD"
           value: "nsroot"
         - name: "EULA"
           value: "yes"
        args:
          - --ingress-classes
           Citrix
	   my-custom-class
	  - --default-ssl-certificate
          default/default-cert 
        imagePullPolicy: IfNotPresent
