apiVersion: citrix.com/v1
kind: rewritepolicy
metadata:
  name: block-ie-traffic
spec:
  responder-policies:
    - servicenames:
        - frontend
      responder-policy:
        respondwith:
          http-payload-string: '"HTTP/1.1 401 <h1> Internet Explorer not supported. Please try Chrome, Mozilla, Safari or Microsoft Edge browser </h1>"'
        respond-criteria: 'http.req.header("user-agent").set_text_mode(ignorecase).contains("trident")'
        comment: 'block Internet Explorer traffic'
