apiVersion: v1
kind: DeploymentConfig
metadata:
  name: cic
spec:
  replicas: 1
  selector:
    router: cic
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 0
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      name: cic
      labels:
        router: cic
    spec:
      serviceAccount: cpx
      containers:
      - name: cic
        # Change the image name with quay image
        image: "in-docker-reg.eng.citrite.net/cic-dev/cic:280"
        securityContext:
          privileged: true
        env:
        - name: "EULA"
          value: "yes"
        # Set NetScaler NSIP/SNIP, SNIP in case of HA (mgmt has to be enabled)
        - name: "NS_IP"
          value: "10.217.212.246"
        # Set NetScaler VIP that receives the traffic
        - name: "NS_VIP"
          value: "10.217.212.239"
        # Set username for Nitro
        - name: "NS_USER"
          value: "nsroot"
        # Set user password for Nitro
        - name: "NS_PASSWORD"
          value: "nsroot"
        - name: "NS_APPS_NAME_PREFIX"
          value: "oc-"
        args:
        - --default-ssl-certificate
          default/default-cert
        - --ingress-classes
          Citrix
          my-custom-class
        imagePullPolicy: Always

