apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-app
  labels:
      name: ssl-app
      app: ssl-app
spec:
  selector:
    matchLabels:
       app: ssl-app
  replicas: 2
  template:
    metadata:
      labels:
        name: ssl-app
        app: ssl-app
    spec:
      containers:
      - name: ssl-app
        image: quay.io/sample-apps/cnn-website:v1.0.0
        ports:
        - name: http-80
          containerPort: 80
        - name: https-443
          containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: ssl-app
  labels:
    app: ssl-app
spec:
  ports:
  - name: http-80
    port: 80
    targetPort: 80
  - name: https-443
    port: 443
    targetPort: 443
  selector:
    name: ssl-app
---