apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logproxy
  labels:
      name: logproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: logproxy
    spec:
      containers:
      - name: logproxy
        image: in-docker-reg.eng.citrite.net/cpx-dev/logproxy:v5
        env:
         - name: "TracingServer"
           value: "zipkin:9411/api/v1/spans"
           #value: "10.106.76.211:9411/api/v1/spans"
        ports:
        - name: logproxy-5557
          containerPort: 5557
        - name: logproxy-5563
          containerPort: 5563
---
apiVersion: v1
kind: Service
metadata:
  name: logproxy
spec:
  clusterIP: None
  ports:
  - name: logproxy-5557
    port: 5557
  - name: logproxy-5563
    port: 5563
  selector:
    name: logproxy
---
