apiVersion: citrix.com/v1
kind: rewritepolicy
metadata:
  name: targeturlrewrite 
spec:
  rewrite-policies:
    - servicenames: 
        - citrix-svc
        - coffee-svc 
      logpackets:
        logexpression: "http.req.url"
        loglevel: INFORMATIONAL
      rewrite-policy:
        operation: replace
        target: 'http.req.url'
        modify-expression: '"new-url-for-the-application"'
        comment: 'Target URL Rewrite - rewrite the url of the HTTP request'
        direction: REQUEST
        rewrite-criteria: 'http.req.is_valid'
