apiVersion: v1
kind: ConfigMap
metadata:
  name: coe-config-es
data:
  lstreamd_default.conf: |
    {
        "Endpoints": {
            "ES": {
                "ServerUrl": "elasticsearch.default.svc.cluster.local:9200",
                "IndexPrefix":"adc_coe",
                "IndexInterval": "daily",
                "RecordType": {
                    "HTTP": "all",
                    "TCP": "all",
                    "SWG": "all",
                    "VPN": "all",
                    "NGS": "all",
                    "ICA": "all",
                    "APPFW": "none",
                    "BOT": "none",
                    "VIDEOOPT": "none",
                    "BURST_CQA": "none",
                    "SLA": "none",
                    "MONGO": "none"
                },
                "ProcessAlways": "no",
                "ProcessYieldTimeOut": "500",
                "MaxConnections": "512",
                "ElkMaxSendBuffersPerSec": "64",
                "JsonFileDump": "no"
            }
        }
    }
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coe-es
  labels:
    app: coe-es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coe-es
  template:
    metadata:
      name: coe-es
      labels:
        app: coe-es
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5563"
    spec:
      containers:
        - name: coe-es
          image: "quay.io/citrix/citrix-observability-exporter:1.2.001"
          imagePullPolicy: Always
          securityContext:
            privileged: true
          ports:
            - containerPort: 5557
              name: lstream
            - containerPort: 5563
              name: rest
          volumeMounts:
            - name: lstreamd-config-es
              mountPath: /var/logproxy/lstreamd/conf/lstreamd_default.conf
              subPath: lstreamd_default.conf
            - name: core-data
              mountPath: /cores/
      volumes:
        - name: lstreamd-config-es
          configMap:
            name: coe-config-es
        - name: core-data
          emptyDir: {}
---
# Citrix-observability-exporter headless service
apiVersion: v1
kind: Service
metadata:
  name: coe-es
  labels:
    app: coe-es
spec:
  clusterIP: None
  ports:
    - port: 5557
      protocol: TCP
      name: lstreamd
    - port: 5563
      protocol: TCP
      name: rest
  selector:
      app: coe-es
---
# Citrix-observability-exporter NodePort service
apiVersion: v1
kind: Service
metadata:
  name: coe-es-nodeport
  labels:
    app: coe-es
    service-type: citrix-adc-monitor
spec:
  type: NodePort
  ports:
    - port: 5557
      protocol: TCP
      name: lstreamd
      nodePort: 32583
    - port: 5563
      protocol: TCP
      name: rest
      nodePort: 30879
  selector:
      app: coe-es
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: citrix-adc-servicemonitor
  labels:
    servicemonitor: citrix-adc
spec:
  endpoints:
  - interval: 30s
    port: rest
  selector:
    matchLabels:
      service-type: citrix-adc-monitor
  namespaceSelector:
    matchNames:
    - monitoring
    - default
