apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vips.citrix.com
spec:
  group: citrix.com
  version: v1
  names:
    kind: vip
    plural: vips
    singular: vip
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Status
      type: string
      description: "Current Status of the CRD"
      JSONPath: .status.state
    - name: Message
      type: string
      description: "Status Message"
      JSONPath: .status.status_message
  additionalPrinterColumns:
  - JSONPath: .spec.ipaddress
    name: VIP
    type: string
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            ipaddress:
              type: string
            name:
              type: string
            kind:
              type: string
              enum: ["service", "ingress"]
            description:
              type: string
