apiVersion: citrix.com/v1
kind: rewritepolicy
metadata:
  name: whitelisturls
  namespace: default
spec:
  responder-policies:
    - servicenames:
        - front-end-headless
      responder-policy:
        respondwith: 
          http-payload-string: '"HTTP/1.1 403 Forbidden\r\n\r\n" + "Client: " + CLIENT.IP.SRC + " is not authorized to access URL:" + HTTP.REQ.URL.HTTP_URL_SAFE +"\n"+"This policy for your network prevents your request from being allowed at this time. Please contact your administrator if you feel this is incorrect.\r\n</h1>"'
        respond-criteria: '!client.ip.src.TYPECAST_text_t.equals_any("allowlistip")'
        comment: 'Allowlist a list of IP addresses'
    
        
  patset:
    - name: allowlistip 
      values: [ '172.17.128.129',  '10.105.158.195' ]
