#Source: https://github.com/citrix/citrix-k8s-ingress-controller/tree/master/deployment/gcp/manifest
#Cluster role bindings required by CPX
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cpx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cpx
subjects:
- kind: ServiceAccount
  name: cpx
  namespace: demoapp