apiVersion: v1
kind: ConfigMap
metadata:
  name: cic-configmap
  namespace: tier-2-adc
data:
   LOGLEVEL: 'debug'
   NS_ANALYTICS_CONFIG: |
     distributed_tracing:
       enable: 'true'
       samplingrate: 100
     endpoint:
       server: '10.105.158.151'
     timeseries:
       port: 30071
       metrics:
         enable: 'true'
         mode: 'prometheus'
       auditlogs:
         enable: 'true'
       events:
         enable: 'true'
     transactions:
       enable: 'true'
       port: 30026
