apiVersion: v1
kind: ConfigMap
metadata:
  name: coe-config
data:
  lstreamd_default.conf: |
    {
        "Endpoints": {
            "ES": {
                "ServerUrl": "elasticsearch.monitoring.svc.cluster.local:9200",
                "IndexPrefix":"adc_coe",
                "IndexInterval": "daily",
                "RecordType": {
                    "HTTP": "all",
                    "TCP": "all",
                    "SWG": "all",
                    "VPN": "all",
                    "NGS": "all",
                    "ICA": "all",
                    "APPFW": "none",
                    "BOT": "none",
                    "VIDEOOPT": "none",
                    "BURST_CQA": "none",
                    "SLA": "none",
                    "MONGO": "none"
                },
                "ProcessAlways": "no",
                "ProcessYieldTimeOut": "500",
                "MaxConnections": "512",
                "ElkMaxSendBuffersPerSec": "64",
                "JsonFileDump": "no"
            },
            "ZIPKIN": {
                "ServerUrl": "zipkin.monitoring.svc.cluster.local:9411/api/v1/spans"
            }
        }
    }
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coe
  labels: 
    app: coe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coe
  template:
    metadata:
      name: coe
      labels:
        app: coe
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5563"
    spec:
      containers:
        - name: coe
          image: "quay.io/citrix/citrix-observability-exporter:1.2.001"
          imagePullPolicy: Always
          ports:
            - containerPort: 5557
              name: lstream
            - containerPort: 5563
              name: rest
          volumeMounts:
            - name: lstreamd-config
              mountPath: /var/logproxy/lstreamd/conf/lstreamd_default.conf
              subPath: lstreamd_default.conf
            - name: core-data
              mountPath: /cores/
      volumes:
        - name: lstreamd-config
          configMap:
            name: coe-config
        - name: core-data
          emptyDir: {}
---
# Citrix-observability-exporter NodePort service
apiVersion: v1
kind: Service
metadata:
  name: coe
  labels:
    app: coe
spec:
  type: NodePort
  ports:
    - port: 5557
      nodePort: 30026
      protocol: TCP
      name: lstreamd
    - port: 5563
      nodePort: 30071
      protocol: TCP
      name: rest
  selector: 
      app: coe
