kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cpx
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "ingresses", "pods", "secrets"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["ingresses", "ingresses/status"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cpx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cpx
subjects:
- kind: ServiceAccount
  name: cpx
  namespace: tier-2-adc

