apiVersion: citrix.com/v1beta1
kind: ratelimit
metadata:
  name: throttle-req-per-clientip
spec:
  servicenames:
    - coffee-beverage
  selector_keys:
   basic:
    per_client_ip: true
  req_threshold: 1
  timeslice: 50000
  throttle_action: "RESPOND"