apiVersion: v1
name: pg-datastore
description: Deploys a basic single PostgreSQL stateful database with custom configurations.
version: 1
appVersion: 2.0
keywords:
- postgresql
- postgres
- database
- sql
- custom-config
home: https://www.crunchydata.com/
icon: https://www.crunchydata.com/images/logo.svg
sources:
- https://github.com/CrunchyData/crunchy-containers
