name: custom-statefulset
container:
  port: 5432
  name: custom-config
credentials:
  primary: "netscalermas$123"
  root: "netscalermas$123"
  user: "netscalermas$123"
serviceType: ClusterIP
image:
  repository: crunchydata
  container: crunchy-postgres
  tag: centos7-10.5-2.1.0
resources:
  cpu: 1000m
  memory: 1048Mi
configMap:
  name: custom-config
storage:
   type: hostDirectoryasdf
   nfsServer: "NA"
   size: 10Gi
   path: "/var/pg-data"
