{
 "title": "NetScaler Stats",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   { "name": "datasource_prometheus", "label": "datasource_prometheus", "query": "prometheus" },
   {
    "name": "lbvservers",
    "label": "lbvservers",
    "query": "label_values(netscaler_lb_vserver_hits_total, lb_vserver_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "LB vserver Hits Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "netscaler_lb_vserver_hits_rate" }
   ]
  },
  {
   "title": "LB vserver Hits Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "netscaler_lb_vserver_hits_total"
    }
   ]
  },
  {
   "title": "CPU Utilization Percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "netscaler_cpu_usage_percent" }
   ]
  },
  {
   "title": "Memory Utilization Percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "netscaler_memory_usage_percent" }
   ]
  }
 ]
}