apiVersion: v1
kind: Service
metadata:
  name: mgmt-monit
  labels:
    app: mgmt-monit
    tier: backend
spec:
  type: NodePort
  externalTrafficPolicy: "Local"
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
    nodePort: 30001
    name: ssh
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30002
    name: http
  - port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 30003
    name: https
  - port: 162
    protocol: UDP
    targetPort: 162
    nodePort: 31001
    name: snmp
  - port: 161
    protocol: UDP
    targetPort: 161
    nodePort: 31502
    name: snmp-agent
  - port: 514
    protocol: UDP
    targetPort: 514
    nodePort: 31002
    name: syslog
  - port: 4739
    protocol: UDP
    targetPort: 4739
    nodePort: 31003
    name: ipfix
  - port: 5557
    protocol: TCP
    targetPort: 5557
    nodePort: 31557
    name: logstream1
  - port: 5558
    protocol: TCP
    targetPort: 5558
    nodePort: 31558
    name: logstream2
  - port: 5563
    protocol: TCP
    targetPort: 5563
    nodePort: 31563
    name: restcollector
  - port: 6565
    protocol: TCP
    targetPort: 6565
    nodePort: 31565
    name: k8s-event-listener
  selector:
    app: mgmt-monit
    tier: backend
