apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdc
spec:
  selector:
    matchLabels:
      app: sdc
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: sdc
        tier: backend
    spec:
      containers:
      - name: sdc
        {{ if not .Values.image.repository }}
        dummy1: {{ required "A valid repository required!" .Values.image.repository }}
        dummy2: {{ required "A valid tag entry required!" .Values.image.tag }}
        {{ else }}
        {{ if eq .Values.image.repository "local"}}
        image: adm-sdc:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: IfNotPresent
        {{ else if eq .Values.image.repository "sjc"}}
        image: adm-local-docker-sdc.sjc-repo.citrite.net/adm-local-docker-sdc:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: Always
        {{ else if eq .Values.image.repository "blr"}}
        image: adm-local-docker-sdc.blr-repo.citrite.net/adm-local-docker-sdc:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: Always
        {{ else if eq .Values.image.repository "quay.io"}}
        image: quay.io/citrixadmtp/sdc:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: Always
        {{ end }}
        {{ end }}
        env:
        - name: POSTGRES_HOST
          value: {{ required "A valid postgresHost required!" .Values.postgres.host | quote }}
        - name: POSTGRES_PORT
          value: {{ .Values.postgres.port | default "5454" | quote}}
        - name: DB_CONNECTION_STR
          value: "generic_connection_string:DRIVER=PostgreSQL_unixODBC;DATABASE=mpsdb;SERVER={{ .Values.postgres.host }};PORT={{ .Values.postgres.port }};UID=mpsroot;PWD=netscalermas$123;MaxVarcharSize=4096;"        
        - name: NFP_HOST
          value: "nfprovisioning"
        - name: NFP_PORT
          value: "80"
        - name: KAD_HOST
          value: "k8sadapter"
        - name: KAD_PORT
          value: "80"
        - name: MGMT_MONIT_HOST
          value: "mgmt-monit"
        ports:
        - containerPort: 5800
        supplementalGroups: [0]
      {{ if eq .Values.image.repository "quay.io"}}
      imagePullSecrets:
      - name: citrixadm-pull-secret
      {{ end }}
