apiVersion: v1
kind: Service
metadata:
  name: dataprocessing
  labels:
    app: dataprocessing
    tier: backend
spec:
  type: NodePort
  ports:
  #DataProcessor runs on 6565 and can be accessed by other containers on 6565
  - port: 6565
    targetPort: 6565
  selector:
    app: dataprocessing
    tier: backend
