apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphqlapi
spec:
  selector:
    matchLabels:
      app: graphqlapi
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: graphqlapi
        tier: backend
    spec:
      containers:
      - name: gql
        {{ if not .Values.image.repository }}
        dummy1: {{ required "A valid repository required!" .Values.image.repository }}
        dummy2: {{ required "A valid tag entry required!" .Values.image.tag }}
        {{ else }}
        {{ if eq .Values.image.repository "local"}}
        image: adm-graphqlapi:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: IfNotPresent
        {{ else if eq .Values.image.repository "sjc"}}
        image: adm-local-docker-dataquery.sjc-repo.citrite.net/adm-local-docker-dataquery:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: Always
        {{ else if eq .Values.image.repository "blr"}}
        image: adm-local-docker-dataquery.blr-repo.citrite.net/adm-local-docker-dataquery:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: Always
        {{ else if eq .Values.image.repository "quay.io"}}
        image: quay.io/citrixadmtp/dataquery:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: Always
        {{ end }}
        {{ end }}
        env:
        - name: DEPLOYMENT_TYPE
          {{ if not .Values.deploymentType }}
          dummy1: {{ required "A valid deploymentType required!" .Values.deploymentType }}
          {{ else }}
          {{ if or (eq .Values.deploymentType "onprem") (eq .Values.deploymentType "service") }}
          value: {{ .Values.deploymentType }}
          {{ else }}
          dummy1: {{ required "value of deploymentType can be onprem or service!" .Values.dummy }}
          {{ end }}
          {{ end }}        
        - name: POSTGRES_HOST
          value: {{ required "A valid postgresHost required!" .Values.postgres.host | quote }}
        - name: POSTGRES_PORT
          value: {{ .Values.postgres.port | default "5454" | quote}}
        ports:
        - containerPort: 6567
      {{ if eq .Values.image.repository "quay.io"}}
      imagePullSecrets:
      - name: citrixadm-pull-secret
      {{ end }}
