apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    tier: frontend
spec:
  type: NodePort
  #type: NodePort
  ports:
  - port: 5900
    targetPort: 5900
    nodePort: 30008
    name: http
  selector:
    app: frontend
    tier: frontend
