apiVersion: v1
kind: Service
metadata:
  name: sdc
  labels:
    app: sdc
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5800
  selector:
    app: sdc
    tier: backend
