apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataprocessing
spec:
  selector:
    matchLabels:
      app: dataprocessing
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: dataprocessing
        tier: backend
    spec:
      containers:
      - name: dp
        {{ if not .Values.image.repository }}
        dummy1: {{ required "A valid repository required!" .Values.image.repository }}
        dummy2: {{ required "A valid tag entry required!" .Values.image.tag }}
        {{ else }}
        {{ if eq .Values.image.repository "local"}}
        image: adm-dataprocessing:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: IfNotPresent
        {{ else if eq .Values.image.repository "sjc"}}
        image: adm-local-docker-dataprocessing.sjc-repo.citrite.net/adm-local-docker-dataprocessing:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: Always
        {{ else if eq .Values.image.repository "blr"}}
        image: adm-local-docker-dataprocessing.blr-repo.citrite.net/adm-local-docker-dataprocessing:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: Always
        {{ else if eq .Values.image.repository "quay.io"}}
        image: quay.io/citrixadmtp/dataprocessing:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: Always
        {{ end }}
        {{ end }}
        env:
        - name: DEPLOYMENT_TYPE
          {{ if not .Values.deploymentType }}
          dummy1: {{ required "A valid deploymentType required!" .Values.deploymentType }}
          {{ else }}
          {{ if or (eq .Values.deploymentType "onprem") (eq .Values.deploymentType "service") }}
          value: {{ .Values.deploymentType }}
          {{ else }}
          dummy1: {{ required "value of deploymentType can be onprem or service!" .Values.dummy }}
          {{ end }}
          {{ end }}        
        - name: POSTGRES_HOST
          value: {{ required "A valid postgresHost required!" .Values.postgres.host | quote }}
        - name: POSTGRES_PORT
          value: {{ .Values.postgres.port | default "5454" | quote}}
        - name: REDIS_HOST
          value: {{ required "A valid redis host required!" .Values.redis.host | quote }}
        - name: REDIS_PORT
          value: {{ .Values.redis.port | default "6379" | quote}}          
        - name: KAD_HOST
          value: "k8sadapter"
        ports:
        - containerPort: 6565
      {{ if eq .Values.image.repository "quay.io"}}
      imagePullSecrets:
      - name: citrixadm-pull-secret
      {{ end }}
