apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adm-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: {{ required "A storage size is required!" .Values.storage.size }}
  storageClassName: adm-storage
