apiVersion: v1
kind: Service
metadata:
  name: nfprovisioning
  labels:
    app: nfprovisioning
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9801
  selector:
    app: nfprovisioning
    tier: backend
