apiVersion: v1
kind: Service
metadata:
  name: aaad
  labels:
    app: aaad
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8766
    targetPort: 8766
  selector:
    app: aaad
    tier: backend
