apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-bootstrapper
spec:
  selector:
    matchLabels:
      app: ingress-bootstrapper
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: ingress-bootstrapper
        tier: backend
    spec:
      containers:
      - name: ingress-bootstrapper
        {{ if not .Values.image.repository }}
        dummy1: {{ required "A valid repository required!" .Values.image.repository }}
        dummy2: {{ required "A valid tag entry required!" .Values.image.tag }}
        {{ else }}
        {{ if eq .Values.image.repository "local"}}
        image: adm-ingress-bootstrapper:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: IfNotPresent
        {{ else if eq .Values.image.repository "sjc"}}
        image: adm-local-docker-ingress-bootstrapper.sjc-repo.citrite.net/adm-local-docker-ingress-bootstrapper:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: Always
        {{ else if eq .Values.image.repository "blr"}}
        image: adm-local-docker-ingress-bootstrapper.blr-repo.citrite.net/adm-local-docker-ingress-bootstrapper:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: Always
        {{ else if eq .Values.image.repository "quay.io"}}
        image: quay.io/citrixadmtp/ingress-bootstrapper:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: Always
        {{ end }}
        {{ end }}
        env:
        - name: APPLICATION_ID
          value: {{ required "A valid applicationID required!" .Values.applicationID | quote }}
        - name: INGRESS_ADC_IP
          value: {{ required "A valid ingressADCIP required!" .Values.ingressADCIP | quote }}
        - name: INGRESS_ADC_USERNAME
          value: {{ required "A valid ingressADCUsername required!" .Values.ingressADCUsername | quote }}
        - name: INGRESS_ADC_PASSWORD
          value: {{ required "A valid ingressADCPassword required!" .Values.ingressADCPassword | quote }}
        - name: INGRESS_FRONTEND_IP
          value: {{ required "A valid ingressIP required!" .Values.ingressIP | quote }}
      {{ if eq .Values.image.repository "quay.io"}}
      imagePullSecrets:
      - name: citrixadm-pull-secret
      {{ end }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: abs
rules:
  - apiGroups: [""]
    resources: ["nodes", "events"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: abs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: abs
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
apiVersion: rbac.authorization.k8s.io/v1
