apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
      - name: fe
        {{ if not .Values.image.repository }}
        dummy1: {{ required "A valid repository required!" .Values.image.repository }}
        dummy2: {{ required "A valid tag entry required!" .Values.image.tag }}
        {{ else }}
        {{ if eq .Values.image.repository "local"}}
        image: adm-frontend:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: IfNotPresent
        {{ else if eq .Values.image.repository "sjc"}}
        image: adm-local-docker-fe.sjc-repo.citrite.net/adm-local-docker-fe:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: Always
        {{ else if eq .Values.image.repository "blr"}}
        image: adm-local-docker-fe.blr-repo.citrite.net/adm-local-docker-fe:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: Always
        {{ else if eq .Values.image.repository "quay.io"}}
        image: quay.io/citrixadmtp/fe:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: Always
        {{ end }}
        {{ end }}
        env:
        - name: MGMT_MONIT_HOST
          value: mgmt-monit
        - name: REDIS_HOST
          value: {{ required "A valid redis host required!" .Values.redis.host | quote }}
        - name: REDIS_PORT
          value: {{ .Values.redis.port | default "6379" | quote}}
        - name: STYLEBOOKS_HOST
          value: "stylebooks" 
        - name: SDC_HOST
          value: "sdc"
        - name: KAD_HOST
          value: "k8sadapter"
        - name: NFP_HOST
          value: "nfp"
        - name: DEPLOYMENT_TYPE
          {{ if not .Values.deploymentType }}
          dummy1: {{ required "A valid deploymentType required!" .Values.deploymentType }}
          {{ else }}
          {{ if or (eq .Values.deploymentType "onprem") (eq .Values.deploymentType "service") }}
          value: {{ .Values.deploymentType }}
          {{ else }}
          dummy1: {{ required "value of deploymentType can be onprem or service!" .Values.dummy }}
          {{ end }}
          {{ end }}
        ports:
        - containerPort: 5900
      {{ if eq .Values.image.repository "quay.io"}}
      imagePullSecrets:
      - name: citrixadm-pull-secret
      {{ end }}
