apiVersion: v1
kind: Service
metadata:
  labels:
    name: sentinel
    role: service
  name: redis-sentinel
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    redis-sentinel: "true"
