---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cpx
rules:
  - apiGroups: [""]
    resources: ["namespaces", "services", "endpoints", "ingresses", "pods", "secrets","nodes", "routes", "routes/status", "tokenreviews", "subjectaccessreviews"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["ingresses", "ingresses/status"]
    verbs: ["*"]
  - apiGroups: ["citrix.com"]
    resources: ["rewritepolicies","continuousdeployments"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments","replicasets"]
    verbs: ["*"]
  - apiGroups: ["citrix.com"]
    verbs: ["*"]
    resources: ["vips"]
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cpx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cpx
subjects:
- kind: ServiceAccount
  name: cpx
  namespace: beverages
apiVersion: rbac.authorization.k8s.io/v1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpx
  namespace: beverages
---
apiVersion: v1
kind: Pod
metadata:
  name: cic-vpx
  labels:
    app: cic-vpx
spec: 
      serviceAccountName: cpx
      containers:
      - name: cic-vpx
        image: "quay.io/citrix/citrix-k8s-ingress-controller:1.7.6"
        env:
         # Set NetScaler NSIP/SNIP, SNIP in case of HA (mgmt has to be enabled) 
         - name: "NS_IP"
           value: "10.105.158.148"
         - name: "NS_VIP"
           value: "10.105.158.197"
         # Set username for Nitro
         # Set log level
         - name: "NS_ENABLE_MONITORING"
           value: "YES"
         - name: "NS_USER"
           value: "nsroot"
         - name: "NS_PASSWORD"
           value: "Toorsn123$"
         - name: "ROUTE_LABELS"
           value: "name in (hotdrink,colddrink,guestbook)"
         - name: "EULA"
           value: "yes"
         - name: "LOGLEVEL"
           value: "INFO"
         - name: "NS_APPS_NAME_PREFIX"
           value: "oc142"
        args:
          - --ingress-classes
            Citrix
          - --feature-node-watch
            true
        imagePullPolicy: IfNotPresent
