apiVersion: v1
kind: Service
metadata:
  name: k8sadapter
  labels:
    app: k8sadapter
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8083
  selector:
    app: k8sadapter
    tier: backend
