apiVersion: v1
kind: Service
metadata:
  name: stylebooks
  labels:
    app: stylebooks
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5800
  selector:
    app: stylebooks
    tier: backend
