apiVersion: v1
kind: Service
metadata:
  name: licensing
  labels:
    app: licensing
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 27000
    targetPort: 27000
    nodePort: 30554
    name: mainport
  - port: 7279
    targetPort: 7279
    nodePort: 32474
    name: auxport
  - port: 9080
    targetPort: 9080
    nodePort: 32475
    name: ctrlport
  selector:
    app: licensing
    tier: backend
