apiVersion: v1
kind: ConfigMap
metadata:
  name: cic-configmap
  labels:
    app: citrix-ingress-controller
data:
    LOGLEVEL: 'info'
    NS_PROTOCOL: 'http'
    NS_PORT: '80'
    NS_HTTP2_SERVER_SIDE: 'ON'